### PR TITLE
Fix “Authentication” typo in strings file

### PR DESCRIPTION
**Pull request by infotexture**

### CODE REVIEW

**Comment by efkaesk** [comment]
The string name `biometric_authnetication_failed` could be renamed as well.

**Comment by Hypopheralcus** [comment]
https://github.com/threema-ch/threema-android#contributions

**Comment by dbrgn** [comment]
Hi, thanks for the contribution! For now we don't accept pull requests (GitHub does not allow disabling them, that's why they're still open), but since this is a small change we've applied it internally to our codebase (including the suggestion by @efkaesk). For larger contributions, please follow the guide at https://threema.ch/en/open-source/contributions/!

**Comment by michael1900** [comment]
You need to add HMS! It is not acceptable that Huawei users, without Google, can not use this app. And not, polling "feature" is not a good solution, it's the worst solution. I will continue to write you until you don't add Huawei Mobile Services. 
Or found a workaround to this problem: https://github.com/microg/GmsCore/issues/1334

Fix it!

**Comment by ralf1307** [comment]
"I will continue to write you until you don't add Huawei Mobile Services" 
That sounds like a threat :)

As this is now an open source project you could try to find a solution yourself and send it to threema Gmbh.
(or write your problem to [support](https://threema.ch/en/support) or the [inofficial forum](https://threema-forum.de/))
But just writing something somewhere it doesn't belong is not the solution.

**Comment by michael1900** [comment]
> "I will continue to write you until you don't add Huawei Mobile Services"
> That sounds like a threat :)
> 
> As this is now an open source project you could try to find a solution yourself and send it to threema Gmbh.
> (or write your problem to [support](https://threema.ch/en/support) or the [inofficial forum](https://threema-forum.de/))
> But just writing something somewhere it doesn't belong is not the solution.

Believe me, just write theme in everywhere, email, forum, support through form, etc..

**Comment by mimiks** [comment]
> > "I will continue to write you until you don't add Huawei Mobile Services"

> > And YES, i am very very angry, sad and tired.

> So, at least for Huawei Phone implement the C2DM for Push Notifications so we can use Microg:
> [microg/GmsCore#1334 (comment)](https://github.com/microg/GmsCore/issues/1334#issuecomment-751639139)
> When Threema see that can not it's possible to use FCM, then enable C2DM for Huawei Phone without Google.

@michael1900 You seem to be ill-informed.
- C2DM was discontinued for existing applications and completely shut down on October 20, 2015. [https://en.wikipedia.org/wiki/Android_Cloud_to_Device_Messaging](url)
- HMS Push is a binary library by a Chinese company. Do you really want this to be part of an app that's all about privacy?

Threema **does have** an alternative to Push. It's called polling. Simply enable it and set it to 5 minutes.

And last but not least: This is a pull request and not a discussion forum for end-user support. Please don't abuse it.

**Pull request closed without merging**
