### PR TITLE
Hungarian translation added

### PR DESCRIPTION
**Pull request by Gabor-B**
## Description

Grüezi Threema-Team, I have created the hungarian translation for the Android Threema app, alongside with the necessary other changes. If I have missed something, please tell me or feel free to adjust the PR.
The app contained a suprisingly high amount of strings, I tried my best to make it properly, it was quite an amount of work involved. I could not test the whole translation, as Threema refused to continue the setup process due to the AppStore check failing (I bought my copy from the site).
I used the German translation as reference. In the process I have also found a couple of typos in he German translation, I hope its not a big problem that I submit them in this PR, not through onesky.

## Checklist

- [x] I signed the [Contributor License Agreement](https://threema.ch/en/open-source/cla)
- [x] All changes in this pull request were made by me, I own the full copyright
      for all these changes

### CODE REVIEW

**Comment by threema-maurus** [comment]
Dear @Gabor-B 
Thank you very much for you contribution!
May we kindly ask you to nevertheless sign the CLA? Such a translation represents a considerable amount of work and is anything but trivial.
To build a version of the app that you can use with a Threema Shop license, you will need to select the build variant "store_threema_Release".

**Comment by Gabor-B** [comment]
The CLA is signed now

**Comment by Gabor-B** [comment]
I created a store build and tested the translation. I optimized some strings, now I consider the translation complete.
The CLA was signed, I dont know why its shown otherwise.

**Review by threema-maurus — APPROVED** [review]

**Comment by threema-maurus** [comment]
Thank you! Your contribution has been merged upstream and uploaded to OneSky.
If you have future changes to the translation, please fix them in the OneSky tool directly as this is our master for all translations. It can be found here: https://threema.oneskyapp.com/collaboration/
Thanks again and kellemes délutánt!

**Pull request closed without merging**
